version: "3.9"
services:
  backend1:
    build: .
    ports:
      - "10001:9999"
    depends_on:
      - redis
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "90MB"
    networks:
      - payment-processor

  backend2:
    build: .
    ports:
      - "10002:9999"
    depends_on:
      - redis
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "90MB"
    networks:
      - payment-processor

  worker:
    build: .
    command: ["node", "src/workers/paymentProcessorWorker.js"]
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"
    networks:
      - payment-processor

  redis:
    image: redis:7-alpine
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"
    networks:
      - payment-processor

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha123
      POSTGRES_DB: rinhadb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "60MB"
    networks:
      - payment-processor

  nginx:
    image: nginx:stable-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"
    networks:
      - payment-processor

networks:
  payment-processor:
    external: true