version: "3.9"
services:
  backend1:
    build: .
    ports:
      - "10001:9999"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - UV_THREADPOOL_SIZE=32
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "175MB"
    networks:
      - payment-processor

  backend2:
    build: .
    ports:
      - "10002:9999"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - UV_THREADPOOL_SIZE=32
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "175MB"
    networks:
      - payment-processor

  redis:
    image: redis:7-alpine
    hostname: redis
    command: [
      "redis-server",
      "--appendonly", "no",
      "--save", "",
      "--maxmemory", "80mb",
      "--maxmemory-policy", "allkeys-lru",
      "--tcp-keepalive", "60",
      "--timeout", "0"
    ]
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "80MB"
    networks:
      - payment-processor

  nginx:
    image: nginx:stable-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
    networks:
      - payment-processor

networks:
  payment-processor:
    external: true