version: "3.9"
services:
  backend1:
    build: .
    hostname: backend1
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - UV_THREADPOOL_SIZE=32
      - PORT=9999
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "140MB"
    networks:
      - payment-processor

  backend2:
    build: .
    hostname: backend2
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - UV_THREADPOOL_SIZE=32
      - PORT=9999
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "140MB"
    networks:
      - payment-processor

  redis:
    image: redis:7-alpine
    hostname: redis
    command: [
      "redis-server",
      "--appendonly", "no",
      "--save", "",
      "--maxmemory", "40mb",
      "--maxmemory-policy", "allkeys-lru",
      "--tcp-keepalive", "60",
      "--timeout", "0",
      "--tcp-backlog", "511",
      "--databases", "1"
    ]
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "45MB"
    networks:
      - payment-processor

  nginx:
    image: nginx:stable-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "25MB"
    networks:
      - payment-processor

networks:
  payment-processor:
    external: true
    driver: bridge