version: "3.9"
services:
  backend1:
    build: .
    ports:
      - "10001:9999"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - UV_THREADPOOL_SIZE=32
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "120MB"
    networks:
      - payment-processor

  backend2:
    build: .
    ports:
      - "10002:9999"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - UV_THREADPOOL_SIZE=32
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "120MB"
    networks:
      - payment-processor

  worker:
    build: .
    command: ["npm", "run", "worker"]
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - UV_THREADPOOL_SIZE=32
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "130MB"
    networks:
      - payment-processor

  redis:
    image: redis:8.0.3-alpine
    hostname: redis
    command: [
      "redis-server",
      "--appendonly", "no",
      "--save", "",
      "--maxmemory", "45mb",
      "--maxmemory-policy", "allkeys-lru",
      "--tcp-keepalive", "60",
      "--timeout", "0",
      "--io-threads", "2",
      "--io-threads-do-reads", "yes"
    ]
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50MB"
    networks:
      - payment-processor


  nginx:
    image: nginx:stable-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "70MB"
    networks:
      - payment-processor

networks:
  payment-processor:
    external: true